const listaLinkadaCircular = require('./ListaCircular.js')
const Roulette = require('./solucaoProblema2.js')

console.log("=====Teste Lista Circular=====")
const listaCircular = new listaLinkadaCircular
listaCircular.insert(2)
listaCircular.insert(3)
listaCircular.insert(4)
listaCircular.insert(5)
listaCircular.current()
console.log(listaCircular)

console.log("=====Teste Roleta de Números=====")
const roleta = new Roulette
roleta.addSetor(1)
roleta.addSetor(2)
roleta.addSetor(3)
roleta.addSetor(4)
roleta.addSetor(5)
roleta.addSetor(6)
roleta.spin()
console.log(roleta)
roleta.spin()
console.log(roleta)
roleta.spin()
console.log(roleta)
roleta.spin()
console.log(roleta)
console.log(roleta.isEmpty())
console.log(roleta.size())
console.log(roleta.clear())
console.log(roleta.isEmpty())
console.log(roleta.size())
console.log(roleta.currentSector())
